### ISSUE TITLE
Finnish data split

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon2020/task0-data#2]
There is no training data for Finnish, but Finnish has the largest dataset of any language in the repo. Did the train and dev files get concatenated?

**Comment by ivri** [comment]
Added .trn file (it was missing). Also added one extra family (so, all construction languages/families are there now). We also canonicalized the data (to make sure all tags are in UnMorph format and follow in the same order). We will make some (minor) changes (due to the canonicalization process) in Uralic data during the next couple of days.
